// <autogenerated/>
namespace AzureDevOpsAnalyzer
{
    using System;
    using System.Collections.Generic;

    public class Author
    {
        public string name { get; set; }

        public string email { get; set; }

        public DateTime date { get; set; }
    }

    public class Committer
    {
        public string name { get; set; }

        public string email { get; set; }

        public DateTime date { get; set; }

    }

    public class ChangeCounts
    {
        public int Add { get; set; }

        public int Edit { get; set; }

        public int Delete { get; set; }
    }

    public class Commit
    {
        public string commitId { get; set; }

        public Author author { get; set; }

        public Committer committer { get; set; }

        public string comment { get; set; }

        public ChangeCounts changeCounts { get; set; }

        public string remoteUrl { get; set; }
    }

    public class CommitHistory
    {
        public List<Commit> value { get; set; }
    }
}