// <autogenerated/>
namespace AzureDevOpsAnalyzer;

public class BuildArtifactProperties
{
    public string localpath { get; set; }
    public string artifactsize { get; set; }
}

public class Resource
{
    public string type { get; set; }
    public string data { get; set; }
    public BuildArtifactProperties properties { get; set; }
    public string url { get; set; }
    public string downloadUrl { get; set; }
}

public class BuildArtifacts
{
    public int count { get; set; }
    public List<BuildArtifact> value { get; set; }
}

public class BuildArtifact
{
    public int id { get; set; }
    public string name { get; set; }
    public string source { get; set; }
    public Resource resource { get; set; }
}