// <autogenerated/>
namespace AzureDevOpsAnalyzer;


public class Team
{
    public string collectionurl { get; set; }
    public string id { get; set; }
    public string name { get; set; }
    public string url { get; set; }
    public string description { get; set; }
    public string projectName { get; set; }
    public string identityUrl { get; set; }
    public string projectId { get; set; }
}

public class Teams
{
    public List<Team> value { get; set; }

    public int count { get; set; }
}