// <autogenerated/>
namespace AzureDevOps.Lib;

public class Child
{
    public int id { get; set; }
    public string identifier { get; set; }
    public string name { get; set; }
    public string structureType { get; set; }
    public bool hasChildren { get; set; }
    public List<Child> children { get; set; }
    public string path { get; set; }
    public string url { get; set; }
}

public class AreaPath
{
    public int id { get; set; }
    public string identifier { get; set; }
    public string name { get; set; }
    public string structureType { get; set; }
    public bool hasChildren { get; set; }
    public List<Child> children { get; set; }
    public string path { get; set; }
    public string url { get; set; }
}