// <autogenerated/>
namespace AzureDevOps.Lib;

public class Value
{
    public string id { get; set; }
    public string name { get; set; }
    public string url { get; set; }
    public Project project { get; set; }
    public string remoteUrl { get; set; }
    public string sshUrl { get; set; }
    public string webUrl { get; set; }
    public string defaultBranch { get; set; }
    public double size { get; set; }
    public bool isDisabled { get; set; }
}

public class Repositories
{
    public List<Value> value { get; set; }
    public int count { get; set; }
}