// <autogenerated/>
namespace AzureDevOps.Lib;

public class TeamAreaPathConfig
{
    public string defaultValue { get; set; }
    public List<TeamAreaPath> values { get; set; }
    public string url { get; set; }
    public Links _links { get; set; }
}

public class TeamAreaPath
{
    public string value { get; set; }
    public bool includeChildren { get; set; }
}
