// <autogenerated/>
namespace AzureDevOps.Lib;

public class TeamMember
{
    public bool isTeamAdmin { get; set; }
    public Identity identity { get; set; }
}

public class TeamMembers
{
    public List<TeamMember> value { get; set; }
    public int count { get; set; }
}

public class Identity
{
    public string displayName { get; set; }
    public string url { get; set; }
    public string id { get; set; }
    public string uniqueName { get; set; }
    public string imageUrl { get; set; }
    public string descriptor { get; set; }
}